### ISSUE TITLE
Possible tie-in with TedxRaleigh

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/ideas#15]
Discuss on slack

**Comment by jhibbets** [comment]
What do you think the opportunity is? I have connections with the
organizers.

**Comment by ChrisTheDBA** [comment]
Well, ted talks are all about story telling.  we have a story to tell.  And maybe run a one day/half day workshop.  ted talks inspire and cause people to start thinking.  What if we had a workshop to say something like "You've heard some great talks to inspire you.  let's gather at ???? and continue the discussion".
